/**
 * Adds AfuChat's Android data-sync foreground service to Expo's generated
 * native project. The android directory is generated by Expo CNG, so the
 * service source and manifest entry must be recreated during every prebuild.
 */

const {
  withAndroidManifest,
  withDangerousMod,
  withMainApplication,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SERVICE_NAME = "com.afuchat.mobile.AfuChatDataSyncService";
const MODULE_MARKER = "add(AfuChatDataSyncPackage())";

function withManifest(config) {
  return withAndroidManifest(config, (manifestConfig) => {
    const manifest = manifestConfig.modResults.manifest;
    const application = manifest.application?.[0];
    if (!application) return manifestConfig;

    const permissions = manifest["uses-permission"] ?? (manifest["uses-permission"] = []);
    if (
      !permissions.some(
        (permission) =>
          permission.$?.["android:name"] ===
          "android.permission.FOREGROUND_SERVICE_DATA_SYNC",
      )
    ) {
      permissions.push({
        $: { "android:name": "android.permission.FOREGROUND_SERVICE_DATA_SYNC" },
      });
    }

    const services = application.service ?? (application.service = []);
    const existing = services.find(
      (service) => service.$?.["android:name"] === SERVICE_NAME,
    );
    const service = existing ?? { $: { "android:name": SERVICE_NAME } };
    service.$ = {
      ...service.$,
      "android:enabled": "true",
      "android:exported": "false",
      "android:foregroundServiceType": "dataSync",
      "android:stopWithTask": "false",
    };
    if (!existing) services.push(service);

    return manifestConfig;
  });
}

function withNativeSource(config) {
  return withDangerousMod(config, [
    "android",
    (modConfig) => {
      const projectRoot = modConfig.modRequest.projectRoot;
      const platformRoot = modConfig.modRequest.platformProjectRoot;
      const packageDir = path.join(
        platformRoot,
        "app",
        "src",
        "main",
        "java",
        "com",
        "afuchat",
        "mobile",
      );
      fs.mkdirSync(packageDir, { recursive: true });

      fs.writeFileSync(
        path.join(packageDir, "AfuChatDataSyncService.kt"),
        `package com.afuchat.mobile

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import androidx.core.app.NotificationCompat
import androidx.core.app.ServiceCompat

class AfuChatDataSyncService : Service() {
  companion object {
    const val ACTION_START = "com.afuchat.mobile.action.START_DATA_SYNC"
    const val ACTION_STOP = "com.afuchat.mobile.action.STOP_DATA_SYNC"
    private const val CHANNEL_ID = "afuchat_data_sync"
    private const val NOTIFICATION_ID = 4101
  }

  override fun onCreate() {
    super.onCreate()
    createNotificationChannel()
  }

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    if (intent?.action == ACTION_STOP) {
      stopSelf()
      return START_NOT_STICKY
    }

    val notification = buildNotification()
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
      ServiceCompat.startForeground(
        this,
        NOTIFICATION_ID,
        notification,
        ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC,
      )
    } else {
      startForeground(NOTIFICATION_ID, notification)
    }
    return START_NOT_STICKY
  }

  override fun onDestroy() {
    ServiceCompat.stopForeground(this, ServiceCompat.STOP_FOREGROUND_REMOVE)
    super.onDestroy()
  }

  override fun onBind(intent: Intent?): IBinder? = null

  private fun buildNotification(): Notification {
    return NotificationCompat.Builder(this, CHANNEL_ID)
      .setSmallIcon(applicationInfo.icon)
      .setContentTitle("AfuChat")
      .setContentText("Syncing your data securely")
      .setOngoing(true)
      .setCategory(NotificationCompat.CATEGORY_SERVICE)
      .setPriority(NotificationCompat.PRIORITY_LOW)
      .build()
  }

  private fun createNotificationChannel() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) return
    val channel = NotificationChannel(
      CHANNEL_ID,
      "Data synchronization",
      NotificationManager.IMPORTANCE_LOW,
    )
    channel.description = "Keeps queued AfuChat data safe while it synchronizes."
    getSystemService(NotificationManager::class.java).createNotificationChannel(channel)
  }
}
`,
      );

      fs.writeFileSync(
        path.join(packageDir, "AfuChatDataSyncModule.kt"),
        `package com.afuchat.mobile

import android.content.Intent
import androidx.core.content.ContextCompat
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

class AfuChatDataSyncModule(
  private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {
  override fun getName(): String = "AfuChatDataSync"

  @ReactMethod
  fun start(promise: Promise) {
    try {
      val intent = Intent(reactContext, AfuChatDataSyncService::class.java)
        .setAction(AfuChatDataSyncService.ACTION_START)
      ContextCompat.startForegroundService(reactContext, intent)
      promise.resolve(true)
    } catch (error: Exception) {
      promise.reject("DATA_SYNC_START_FAILED", error)
    }
  }

  @ReactMethod
  fun stop(promise: Promise) {
    try {
      val intent = Intent(reactContext, AfuChatDataSyncService::class.java)
        .setAction(AfuChatDataSyncService.ACTION_STOP)
      reactContext.stopService(intent)
      promise.resolve(true)
    } catch (error: Exception) {
      promise.reject("DATA_SYNC_STOP_FAILED", error)
    }
  }
}
`,
      );

      fs.writeFileSync(
        path.join(packageDir, "AfuChatDataSyncPackage.kt"),
        `package com.afuchat.mobile

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class AfuChatDataSyncPackage : ReactPackage {
  override fun createNativeModules(
    reactContext: ReactApplicationContext,
  ): List<NativeModule> = listOf(AfuChatDataSyncModule(reactContext))

  override fun createViewManagers(
    reactContext: ReactApplicationContext,
  ): List<ViewManager<*, *>> = emptyList()
}
`,
      );

      return modConfig;
    },
  ]);
}

function withPackageRegistration(config) {
  return withMainApplication(config, (applicationConfig) => {
    let contents = applicationConfig.modResults.contents;
    if (!contents.includes("import com.afuchat.mobile.AfuChatDataSyncPackage")) {
      contents = contents.replace(
        "import android.content.res.Configuration",
        "import android.content.res.Configuration\n\nimport com.afuchat.mobile.AfuChatDataSyncPackage",
      );
    }
    if (!contents.includes(MODULE_MARKER)) {
      contents = contents.replace(
        /(\s*\/\/ Packages that cannot be autolinked yet can be added manually here, for example:)/,
        `\n          ${MODULE_MARKER}$1`,
      );
    }
    applicationConfig.modResults.contents = contents;
    return applicationConfig;
  });
}

module.exports = function withDataSyncForegroundService(config) {
  config = withManifest(config);
  config = withNativeSource(config);
  return withPackageRegistration(config);
};